### ISSUE TITLE
hello，可以请教你一个问题吗。。

### ISSUE THREAD

**Issue by chenshiforever** [luoyily/zhihuishu-tool#1]
那个学生首页AES Key是从哪里找出来的呀，我找了好久没找到，emmm

**Comment by luoyily** [comment]
我是通过跟踪接口queryShareCourseInfo中的secretStr进而找到学生首页AES Key的。
你可以在这里查看完整的逆向记录：
https://www.bilibili.com/read/cv15620703

**Comment by chenshiforever** [comment]
非常感谢~~~
